### ISSUE TITLE
Feedback data doesn't make sense! 

### ISSUE THREAD

**Issue by Karin-Sugi** [HebiRobotics/hebi-cpp-examples#78]
Hi, I'm tried to get realtime data with `feedback.getVelocity();` or `feedback.getPosition();`, and tried to print it out, which printed data didn't make sense.

I mean when I set the velocity 0.1 rad/s, the feedback velocity is -1363713688 though scope says actual velocity is around 0.1 rad/s. Also, I checked my command with printf() which return strange velue -1238723712, too. The biggest mistery is feedback velocity and printed command velocity don't match.

How can I get reasonable realtime data (velocity and position) with `feedback.getxxxx()`? Or is it impossible to get reasonable data without log file?

My code is here; 
```
hebi::GroupCommand group_command(group->size());
Eigen::VectorXd velocities(group->size());

velocities[0] = 0.1; // [rad/s]
group_command.setVelocity(velocities);

 // Feedback Command
 hebi::GroupFeedback feedback(group->size());
 group->setFeedbackFrequencyHz(10); // set time of feedback
 
while(ros::ok()){
        group->sendCommand(group_command);
        ROS_INFO("send command: %d [rad/s]", velocities[0]);

        Eigen::VectorXd vel = feedback.getVelocity();
        Eigen::VectorXd pos = feedback.getPosition();
        ROS_INFO("Actual velocity: %d [rad/s]", vel);
        ROS_INFO("Actual position: %d [rad]", pos);

        loop_rate.sleep();
    }
```
Thanks in advance,
Karin

**Comment by iamtesch** [comment]
Note that the `Eigen` matrix library provides matrix and vector types, and we provide the position and velocity as a vector as it will typically have different values for every module in the group.  I believe the issue here is that you are trying to print out the `Eigen` vector type, but treating it as an integer (the `%d` specifier in the `printf` command).  For example, the following code does not actually compile for me using g++ unless I suppress a warning (and crashes if I try to run it with the warning suppressed).

```
#include "Eigen/Dense"
#include <iostream> 
int main()
{
  Eigen::VectorXf a(2);
  a[0] = 0;
  a[1] = 0;
  // ERROR: NEXT LINE INCORRECT AND MAY NOT COMPILE!
  printf("a: %d\n", a);
  printf("a0: %d\n", a[0]);
  printf("a1: %d\n", a[1]);
  return 0;
}
```

If I comment out the line after the "ERROR" commend, then I get the expected values of the vector out.

The two solutions I would recommend are:
(1) Index into the Eigen vector object to retrieve the individual values and format as you wish
(2) use the stream operators provided by Eigen to retrieve a serialized form of the matrix.  For example, the following code prints the feedback to standard out:
```
std::cout << feedback.getVelocity();
```

Let me know if this resolves your problem!

**Comment by Karin-Sugi** [comment]
Hi, it works fine.
Great thanks!
